### ISSUE TITLE
Not possible to use some js expressions functions due to use of esc_attr in add_attributes

### ISSUE THREAD

**Issue by spencer-j** [websevendev/attributes-for-blocks#3]
Thank you for this very usefull plugin: 

At the moment it is not possible to add attributes with expressions for alpine.js like
`:class="{ 'header-menu-sidebar-overlay' : showNav }"`

they results in 
`:class="{ &amp;#039;header-menu-sidebar-overlay&amp;#039; : showBar }"`
or
`x-on:scroll.window="showNav = (window.pageYOffset > 120) ? true : false"`
results in:
`x-on:scroll.window="showBar = (window.pageYOffset &amp;gt; 120) ? true : false"
`
also the attribute name with @scroll:window isn't allowed. @ is shorthand in alpine.js for x-on:

Would be great if there was a filter to remove the  esc_attr function at 
https://github.com/websevendev/attributes-for-blocks/blob/404cc24fcdd6dd640a8c482f9ae80eddd0074d2a/includes/attributes.php#L91

greets spencer

**Comment by websevendev** [comment]
Added filters in 1.0.4:

https://github.com/websevendev/attributes-for-blocks/blob/df64df1e56e0cd14ddcd7030db97f147e0b9f628/includes/attributes.php#L94-L97

They use `esc_attr` by default:

https://github.com/websevendev/attributes-for-blocks/blob/df64df1e56e0cd14ddcd7030db97f147e0b9f628/attributes-for-blocks.php#L28-L29

but you can unhook them from your child theme's `functions.php` or elsewhere:

```php
remove_filter('afb_sanitize_attribute_key', 'esc_attr');
remove_filter('afb_sanitize_attribute_value', 'esc_attr');
```

Let me know if that works for you.

> also the attribute name with @scroll:window isn't allowed. @ is shorthand in alpine.js for x-on:

The `@` sign is used by this plugin to determine if the attribute value should be merged or overridden and will be stripped eventually. You could add an attribute with 2 leading `@`'s (buggy) but it turns out PHP `DOMElement::setAttribute` can't handle this character anyway and throws an error (so it would only work for blocks that are rendered client-side). Could technically fix it with a placeholder and `str_replace` it in, but probably not worth the mess if it's only a shorthand.

**Comment by spencer-j** [comment]
Thank you for the new version,
works for me

> Could technically fix it with a placeholder and str_replace it in, but probably not worth the mess if it's only a shorthand.

so true
